import { defineConfig, globalIgnores } from 'eslint/config';
import nextVitals from 'eslint-config-next/core-web-vitals';
import nextTs from 'eslint-config-next/typescript';

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  globalIgnores([
    '.next/**',
    'out/**',
    'build/**',
    'next-env.d.ts',
    // Vendored DuckDB-Wasm workers — minified third-party code regenerated by
    // scripts/copy-duckdb-assets.mjs at prebuild (gitignored); never linted.
    'public/duckdb/**',
  ]),
]);

export default eslintConfig;
