import type { MetadataRoute } from 'next';
import { SITE_URL } from '@/lib/site-config';

// Required for `output: 'export'` — robots.txt is generated at
// build time and emitted as a static file in out/.
export const dynamic = 'force-static';

/**
 * robots.txt — auto-generated by Next.js. Allows all user-agents
 * (this is a public viewer, indexing is welcome) and points
 * crawlers at the sitemap.
 *
 * Static export: Next.js writes /robots.txt into out/ at build time.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
  };
}
