'use client';

import { useEffect, useState } from 'react';
import { BitcoinChainAdapter } from '@/data/BitcoinChainAdapter';
import { epochFromHeight } from '@/types/block';
import type { LatticeStatus } from '@/types/lattice';

/**
 * LiveStatus — client-side status panel that fetches from the
 * BitcoinChainAdapter on mount. Shared between Grid and Graph; both
 * /status pages mount the same component.
 *
 * For v0.1, the adapter reads from a static `/status.json` written
 * directly to `public/`. For v0.2+, that JSON gets regenerated by
 * the chain-tools pipeline on each block and served from the R2
 * bucket fronted by `NEXT_PUBLIC_CDN_BASE`.
 */

const CDN_BASE = process.env.NEXT_PUBLIC_CDN_BASE ?? '';

export function LiveStatus() {
  const [status, setStatus] = useState<LatticeStatus | null>(null);
  const [phase, setPhase] = useState<'loading' | 'ready' | 'failed'>('loading');

  useEffect(() => {
    const adapter = new BitcoinChainAdapter(CDN_BASE);
    let cancelled = false;
    void adapter.getStatus().then((s) => {
      if (cancelled) return;
      if (s.currentBlock > 0) {
        setStatus(s);
        setPhase('ready');
      } else {
        // currentBlock = 0 from the adapter is its safe-fallback
        // signal; we treat that as "no live data available" to the
        // user rather than "the chain is at genesis".
        setPhase('failed');
      }
    });
    return () => {
      cancelled = true;
    };
  }, []);

  if (phase === 'loading') {
    return (
      <div className="brass-panel rounded-lg p-5">
        <p className="text-mono text-[10px] uppercase tracking-[0.22em] text-[color:var(--color-text-muted)]">
          Live status
        </p>
        <p className="mt-3 text-sm text-[color:var(--color-text-secondary)]">
          Fetching <code className="text-mono text-xs">/status.json</code>…
        </p>
      </div>
    );
  }

  if (phase === 'failed' || !status) {
    return (
      <div className="brass-panel rounded-lg p-5" style={{ borderColor: 'var(--color-amber)' }}>
        <p className="text-mono text-[10px] uppercase tracking-[0.22em] text-[color:var(--color-amber)]">
          Live status · stale
        </p>
        <p className="mt-3 text-sm text-[color:var(--color-text-secondary)]">
          The status sidecar is unreachable or returned an unparseable
          payload. The viewer falls back to fixture data; the chain-tools
          pipeline may not have generated a snapshot yet.
        </p>
      </div>
    );
  }

  const { currentBlock, lastBlockTime, nextBlockEtaMs } = status;
  const epoch = epochFromHeight(currentBlock);
  const halvings = Math.floor(currentBlock / 210_000);
  // Pure render: show the absolute UTC time of the last block. A
  // "seconds ago" computation would require Date.now() in render,
  // which violates react-hooks/purity (renders aren't deterministic
  // when they depend on wall-clock state).
  const lastBlockUtc =
    typeof lastBlockTime === 'number'
      ? new Date(lastBlockTime).toISOString().slice(11, 16) + ' UTC'
      : '—';
  const nextEtaSeconds =
    typeof nextBlockEtaMs === 'number'
      ? `${Math.floor(nextBlockEtaMs / 1000).toLocaleString()} s`
      : '—';

  return (
    <div className="brass-panel rounded-lg p-5">
      <div className="flex items-baseline justify-between gap-3">
        <p className="text-mono text-[10px] uppercase tracking-[0.22em] text-[color:var(--color-brass-bright)]">
          Live status
        </p>
        <span className="status-dot" aria-label="snapshot reachable" />
      </div>
      <p className="text-display mt-3 text-3xl font-semibold leading-none text-[color:var(--color-text-primary)]">
        {currentBlock.toLocaleString()}
      </p>
      <p className="mt-1 text-mono text-xs text-[color:var(--color-text-muted)]">
        epoch {epoch} · {halvings} {halvings === 1 ? 'halving' : 'halvings'} crossed
      </p>
      <dl className="mt-4 grid grid-cols-2 gap-3 text-mono text-xs">
        <Field label="Last block at" value={lastBlockUtc} />
        <Field label="Next ETA" value={nextEtaSeconds} />
      </dl>
    </div>
  );
}

function Field({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <dt className="text-[10px] uppercase tracking-wider text-[color:var(--color-text-muted)]">
        {label}
      </dt>
      <dd className="mt-1 text-[color:var(--color-text-primary)]">{value}</dd>
    </div>
  );
}
